//Employees
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";
export const GET_EMPLOYEES_REQUESTED = "GET_EMPLOYEES_REQUESTED";
export const EMPLOYEES_FAILED = "EMPLOYEES_FAILED";

//WorkLog
export const GET_WORKLOG_SUCCESS = "GET_WORKLOG_SUCCESS";
export const GET_WORKLOG_REQUESTED = "GET_WORKLOG_REQUESTED";
export const WORKLOG_FAILED = "WORKLOG_FAILED";
