//Employees
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";
export const GET_EMPLOYEES_REQUESTED = "GET_EMPLOYEES_REQUESTED";
export const EMPLOYEES_FAILED = "EMPLOYEES_FAILED";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE";
